---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
  namespace: bgd
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"httpd:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"bgd\")].image"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/bgd/httpd 
        name: bgd
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
