apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: httpd
  namespace: bgd
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/openshift/httpd
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: ""
